# Загальні налаштування

timeout: 600s

# Крок 1: Клонування коду з GitHub

steps:
 - name: Clone code
   id: clone_code
   dir: /workspace
   gitClone:
   url: https://github.com/your-organization/your-repo.git

# Крок 2: Встановлення залежностей Python

 - name: Install Python dependencies
   id: install_deps
   dir: /workspace
   entrypoint: sh
   args:
    - -c
    - |
     python3.10 -m pip install -r requirements.txt

# Крок 3: Розгортання функції Google Cloud

 - name: Deploy function
   id: deploy_function
   waitFor: [install_deps]
   dir: /workspace
   entrypoint: sh
   args:
     - -c
     - |
      gcloud functions deploy my-function --runtime python310 --trigger-http --source .